package cn.hehe9.persistent.mapper;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import cn.hehe9.persistent.entity.ComicEpisode;
@Repository
public interface ComicEpisodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_episode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_episode
     *
     * @mbggenerated
     */
    int insert(ComicEpisode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_episode
     *
     * @mbggenerated
     */
    int insertSelective(ComicEpisode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_episode
     *
     * @mbggenerated
     */
    ComicEpisode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_episode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComicEpisode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_episode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComicEpisode record);
    
    /**
	 * 根据条件, 查询记录
	 * @param params
	 * @return
	 */
	List<ComicEpisode> findBy(Map<String, Object> params);

	/**
	 * 根据条件, 统计记录数量
	 *
	 * @param params
	 * @return
	 */
	Integer countBy(Map<String, Object> params);

	/**
	 * 根据最大最小分集号, 查询范围内的分集列表
	 *
	 * @param params
	 * @return
	 */
	List<ComicEpisode> findByRange(Map<String, Object> params);
}