package cn.hehe9.persistent.mapper;

import java.util.List;
import java.util.Map;

import cn.hehe9.persistent.entity.Comic;
import cn.hehe9.persistent.entity.Comic;

public interface ComicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbggenerated
     */
    int insert(Comic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbggenerated
     */
    int insertSelective(Comic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbggenerated
     */
    Comic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Comic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Comic record);
    
	/**
	 * 根据条件, 查询简要信息
	 * @param params
	 * @return
	 */
	public List<Comic> findBriefBy(Map<String, Object> params);

	/**
	 * 根据条件, 查询视频信息
	 * @param params
	 * @return
	 */
	public List<Comic> findBy(Map<String, Object> params);

	/**
	 * 根据条件, 统计视频数量
	 *
	 * @param params
	 * @return
	 */
	public Integer countBy(Map<String, Object> params);

	/**
	 * 按首字母分组查询记录
	 * @return	视频列表
	 */

	public List<Comic> listBriefGroupByFirstChar(Map<String, Object> params);

	/**
	 * 查询视频列表: 排除大数据量的字段
	 */
	public List<Comic> findExceptBigDataBy(Map<String, Object> params);
}