package cn.hehe9.persistent.mapper;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import cn.hehe9.persistent.entity.ComicSource;
@Repository
public interface ComicSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_source
     *
     * @mbggenerated
     */
    int insert(ComicSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_source
     *
     * @mbggenerated
     */
    int insertSelective(ComicSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_source
     *
     * @mbggenerated
     */
    ComicSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComicSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComicSource record);
    
    List<ComicSource> findBy(Map<String, Object> params);
}