package cn.hehe9.persistent.entity;

import java.io.Serializable;
import java.util.Date;

public class ComicEpisode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.comic_id
     *
     * @mbggenerated
     */
    private Integer comicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.episode_no
     *
     * @mbggenerated
     */
    private Integer episodeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.read_page_url
     *
     * @mbggenerated
     */
    private String readPageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.pic_urls
     *
     * @mbggenerated
     */
    private String picUrls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_episode.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comic_episode
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.id
     *
     * @return the value of comic_episode.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.id
     *
     * @param id the value for comic_episode.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.comic_id
     *
     * @return the value of comic_episode.comic_id
     *
     * @mbggenerated
     */
    public Integer getComicId() {
        return comicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.comic_id
     *
     * @param comicId the value for comic_episode.comic_id
     *
     * @mbggenerated
     */
    public void setComicId(Integer comicId) {
        this.comicId = comicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.title
     *
     * @return the value of comic_episode.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.title
     *
     * @param title the value for comic_episode.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.episode_no
     *
     * @return the value of comic_episode.episode_no
     *
     * @mbggenerated
     */
    public Integer getEpisodeNo() {
        return episodeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.episode_no
     *
     * @param episodeNo the value for comic_episode.episode_no
     *
     * @mbggenerated
     */
    public void setEpisodeNo(Integer episodeNo) {
        this.episodeNo = episodeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.read_page_url
     *
     * @return the value of comic_episode.read_page_url
     *
     * @mbggenerated
     */
    public String getReadPageUrl() {
        return readPageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.read_page_url
     *
     * @param readPageUrl the value for comic_episode.read_page_url
     *
     * @mbggenerated
     */
    public void setReadPageUrl(String readPageUrl) {
        this.readPageUrl = readPageUrl == null ? null : readPageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.pic_urls
     *
     * @return the value of comic_episode.pic_urls
     *
     * @mbggenerated
     */
    public String getPicUrls() {
        return picUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.pic_urls
     *
     * @param picUrls the value for comic_episode.pic_urls
     *
     * @mbggenerated
     */
    public void setPicUrls(String picUrls) {
        this.picUrls = picUrls == null ? null : picUrls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.remark
     *
     * @return the value of comic_episode.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.remark
     *
     * @param remark the value for comic_episode.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.create_time
     *
     * @return the value of comic_episode.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.create_time
     *
     * @param createTime the value for comic_episode.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_episode.modify_time
     *
     * @return the value of comic_episode.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_episode.modify_time
     *
     * @param modifyTime the value for comic_episode.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}