package cn.hehe9.persistent.entity;

import java.io.Serializable;
import java.util.Date;

public class Comic extends ComicSource implements Serializable {
	
	// -- 与数据库字段无关的字段 start --
	private String sourceName;
	//-- end --
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.source_id
     *
     * @mbggenerated
     */
    private Integer sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.place
     *
     * @mbggenerated
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.birth_year
     *
     * @mbggenerated
     */
    private String birthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.read_count_weekly
     *
     * @mbggenerated
     */
    private String readCountWeekly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.read_count_total
     *
     * @mbggenerated
     */
    private String readCountTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.story_line
     *
     * @mbggenerated
     */
    private String storyLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.poster_big_url
     *
     * @mbggenerated
     */
    private String posterBigUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.poster_mid_url
     *
     * @mbggenerated
     */
    private String posterMidUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.poster_small_url
     *
     * @mbggenerated
     */
    private String posterSmallUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.icon_url
     *
     * @mbggenerated
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.list_page_url
     *
     * @mbggenerated
     */
    private String listPageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.update_remark
     *
     * @mbggenerated
     */
    private String updateRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.serialize_status
     *
     * @mbggenerated
     */
    private String serializeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.types
     *
     * @mbggenerated
     */
    private String types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.first_char
     *
     * @mbggenerated
     */
    private String firstChar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.rank
     *
     * @mbggenerated
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.hot
     *
     * @mbggenerated
     */
    private Integer hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.id
     *
     * @return the value of comic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.id
     *
     * @param id the value for comic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.source_id
     *
     * @return the value of comic.source_id
     *
     * @mbggenerated
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.source_id
     *
     * @param sourceId the value for comic.source_id
     *
     * @mbggenerated
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.name
     *
     * @return the value of comic.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.name
     *
     * @param name the value for comic.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.author
     *
     * @return the value of comic.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.author
     *
     * @param author the value for comic.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.place
     *
     * @return the value of comic.place
     *
     * @mbggenerated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.place
     *
     * @param place the value for comic.place
     *
     * @mbggenerated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.birth_year
     *
     * @return the value of comic.birth_year
     *
     * @mbggenerated
     */
    public String getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.birth_year
     *
     * @param birthYear the value for comic.birth_year
     *
     * @mbggenerated
     */
    public void setBirthYear(String birthYear) {
        this.birthYear = birthYear == null ? null : birthYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.read_count_weekly
     *
     * @return the value of comic.read_count_weekly
     *
     * @mbggenerated
     */
    public String getReadCountWeekly() {
        return readCountWeekly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.read_count_weekly
     *
     * @param readCountWeekly the value for comic.read_count_weekly
     *
     * @mbggenerated
     */
    public void setReadCountWeekly(String readCountWeekly) {
        this.readCountWeekly = readCountWeekly == null ? null : readCountWeekly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.read_count_total
     *
     * @return the value of comic.read_count_total
     *
     * @mbggenerated
     */
    public String getReadCountTotal() {
        return readCountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.read_count_total
     *
     * @param readCountTotal the value for comic.read_count_total
     *
     * @mbggenerated
     */
    public void setReadCountTotal(String readCountTotal) {
        this.readCountTotal = readCountTotal == null ? null : readCountTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.story_line
     *
     * @return the value of comic.story_line
     *
     * @mbggenerated
     */
    public String getStoryLine() {
        return storyLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.story_line
     *
     * @param storyLine the value for comic.story_line
     *
     * @mbggenerated
     */
    public void setStoryLine(String storyLine) {
        this.storyLine = storyLine == null ? null : storyLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.poster_big_url
     *
     * @return the value of comic.poster_big_url
     *
     * @mbggenerated
     */
    public String getPosterBigUrl() {
        return posterBigUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.poster_big_url
     *
     * @param posterBigUrl the value for comic.poster_big_url
     *
     * @mbggenerated
     */
    public void setPosterBigUrl(String posterBigUrl) {
        this.posterBigUrl = posterBigUrl == null ? null : posterBigUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.poster_mid_url
     *
     * @return the value of comic.poster_mid_url
     *
     * @mbggenerated
     */
    public String getPosterMidUrl() {
        return posterMidUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.poster_mid_url
     *
     * @param posterMidUrl the value for comic.poster_mid_url
     *
     * @mbggenerated
     */
    public void setPosterMidUrl(String posterMidUrl) {
        this.posterMidUrl = posterMidUrl == null ? null : posterMidUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.poster_small_url
     *
     * @return the value of comic.poster_small_url
     *
     * @mbggenerated
     */
    public String getPosterSmallUrl() {
        return posterSmallUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.poster_small_url
     *
     * @param posterSmallUrl the value for comic.poster_small_url
     *
     * @mbggenerated
     */
    public void setPosterSmallUrl(String posterSmallUrl) {
        this.posterSmallUrl = posterSmallUrl == null ? null : posterSmallUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.icon_url
     *
     * @return the value of comic.icon_url
     *
     * @mbggenerated
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.icon_url
     *
     * @param iconUrl the value for comic.icon_url
     *
     * @mbggenerated
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.list_page_url
     *
     * @return the value of comic.list_page_url
     *
     * @mbggenerated
     */
    public String getListPageUrl() {
        return listPageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.list_page_url
     *
     * @param listPageUrl the value for comic.list_page_url
     *
     * @mbggenerated
     */
    public void setListPageUrl(String listPageUrl) {
        this.listPageUrl = listPageUrl == null ? null : listPageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.update_remark
     *
     * @return the value of comic.update_remark
     *
     * @mbggenerated
     */
    public String getUpdateRemark() {
        return updateRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.update_remark
     *
     * @param updateRemark the value for comic.update_remark
     *
     * @mbggenerated
     */
    public void setUpdateRemark(String updateRemark) {
        this.updateRemark = updateRemark == null ? null : updateRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.serialize_status
     *
     * @return the value of comic.serialize_status
     *
     * @mbggenerated
     */
    public String getSerializeStatus() {
        return serializeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.serialize_status
     *
     * @param serializeStatus the value for comic.serialize_status
     *
     * @mbggenerated
     */
    public void setSerializeStatus(String serializeStatus) {
        this.serializeStatus = serializeStatus == null ? null : serializeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.types
     *
     * @return the value of comic.types
     *
     * @mbggenerated
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.types
     *
     * @param types the value for comic.types
     *
     * @mbggenerated
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.first_char
     *
     * @return the value of comic.first_char
     *
     * @mbggenerated
     */
    public String getFirstChar() {
        return firstChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.first_char
     *
     * @param firstChar the value for comic.first_char
     *
     * @mbggenerated
     */
    public void setFirstChar(String firstChar) {
        this.firstChar = firstChar == null ? null : firstChar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.rank
     *
     * @return the value of comic.rank
     *
     * @mbggenerated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.rank
     *
     * @param rank the value for comic.rank
     *
     * @mbggenerated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.hot
     *
     * @return the value of comic.hot
     *
     * @mbggenerated
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.hot
     *
     * @param hot the value for comic.hot
     *
     * @mbggenerated
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.remark
     *
     * @return the value of comic.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.remark
     *
     * @param remark the value for comic.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.create_time
     *
     * @return the value of comic.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.create_time
     *
     * @param createTime the value for comic.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.modify_time
     *
     * @return the value of comic.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.modify_time
     *
     * @param modifyTime the value for comic.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
    
    public String getSourceName() {
		return sourceName;
	}
    
    public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}
}