package cn.hehe9.persistent.entity;

import java.io.Serializable;
import java.util.Date;

public class ComicSource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_source.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_source.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_source.root_url
     *
     * @mbggenerated
     */
    private String rootUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_source.collect_page_url
     *
     * @mbggenerated
     */
    private String collectPageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_source.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_source.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic_source.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comic_source
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_source.id
     *
     * @return the value of comic_source.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_source.id
     *
     * @param id the value for comic_source.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_source.name
     *
     * @return the value of comic_source.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_source.name
     *
     * @param name the value for comic_source.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_source.root_url
     *
     * @return the value of comic_source.root_url
     *
     * @mbggenerated
     */
    public String getRootUrl() {
        return rootUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_source.root_url
     *
     * @param rootUrl the value for comic_source.root_url
     *
     * @mbggenerated
     */
    public void setRootUrl(String rootUrl) {
        this.rootUrl = rootUrl == null ? null : rootUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_source.collect_page_url
     *
     * @return the value of comic_source.collect_page_url
     *
     * @mbggenerated
     */
    public String getCollectPageUrl() {
        return collectPageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_source.collect_page_url
     *
     * @param collectPageUrl the value for comic_source.collect_page_url
     *
     * @mbggenerated
     */
    public void setCollectPageUrl(String collectPageUrl) {
        this.collectPageUrl = collectPageUrl == null ? null : collectPageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_source.remark
     *
     * @return the value of comic_source.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_source.remark
     *
     * @param remark the value for comic_source.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_source.create_time
     *
     * @return the value of comic_source.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_source.create_time
     *
     * @param createTime the value for comic_source.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic_source.modify_time
     *
     * @return the value of comic_source.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic_source.modify_time
     *
     * @param modifyTime the value for comic_source.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}